"""Tests for the CLI interface."""

from __future__ import annotations

from pathlib import Path

from typer.testing import CliRunner

from git_tribe.cli import app

runner = CliRunner()


def test_version_flag():
    result = runner.invoke(app, ["--version"])
    assert result.exit_code == 0
    assert "git-tribe" in result.stdout


def test_scan_command_runs(tmp_git_repo: Path):
    result = runner.invoke(app, ["scan", str(tmp_git_repo)])
    assert result.exit_code == 0


def test_scan_json_output(tmp_git_repo: Path, tmp_path: Path):
    output_file = tmp_path / "report.json"
    result = runner.invoke(
        app, ["scan", str(tmp_git_repo), "--format", "json", "--output", str(output_file)]
    )
    assert result.exit_code == 0
    assert output_file.exists()
    import json

    data = json.loads(output_file.read_text())
    assert "ownership" in data
    assert "bus_factors" in data


def test_scan_markdown_output(tmp_git_repo: Path, tmp_path: Path):
    output_file = tmp_path / "report.md"
    result = runner.invoke(
        app, ["scan", str(tmp_git_repo), "--format", "markdown", "--output", str(output_file)]
    )
    assert result.exit_code == 0
    assert output_file.exists()
    assert "# Git Tribe" in output_file.read_text()


def test_scan_csv_output(tmp_git_repo: Path, tmp_path: Path):
    output_file = tmp_path / "report.csv"
    result = runner.invoke(
        app, ["scan", str(tmp_git_repo), "--format", "csv", "--output", str(output_file)]
    )
    assert result.exit_code == 0
    assert output_file.exists()
    assert "file,author,ownership_pct" in output_file.read_text()


def test_bus_factor_command(tmp_git_repo: Path):
    result = runner.invoke(app, ["bus-factor", str(tmp_git_repo)])
    assert result.exit_code == 0


def test_silos_command(tmp_git_repo: Path):
    result = runner.invoke(app, ["silos", str(tmp_git_repo)])
    assert result.exit_code == 0


def test_codeowners_command(tmp_git_repo: Path, tmp_path: Path):
    output_file = tmp_path / "CODEOWNERS"
    result = runner.invoke(app, ["codeowners", str(tmp_git_repo), "--output", str(output_file)])
    assert result.exit_code == 0
    assert output_file.exists()
    content = output_file.read_text()
    assert "auto-generated by git-tribe" in content


def test_scan_with_since(tmp_git_repo: Path):
    result = runner.invoke(app, ["scan", str(tmp_git_repo), "--since", "1 year ago"])
    assert result.exit_code == 0


def test_unknown_format():
    result = runner.invoke(app, ["scan", ".", "--format", "xml"])
    assert result.exit_code == 1
