"""CODEOWNERS file generator."""

from __future__ import annotations

from pathlib import Path, PurePosixPath

from git_tribe.metrics.ownership import OwnershipEntry


def generate_codeowners(
    ownership: dict[str, list[OwnershipEntry]],
    output_path: Path,
    output_format: str = "github",
) -> None:
    """Generate a CODEOWNERS file from ownership data."""
    # Aggregate to directory level for cleaner output
    dir_owners = _aggregate_to_directories(ownership)

    lines: list[str] = []
    lines.append("# This file is auto-generated by git-tribe")
    lines.append("# https://github.com/git-tribe/git-tribe")
    lines.append("#")
    lines.append(f"# Generated format: {output_format}")
    lines.append("")

    for dir_path in sorted(dir_owners.keys()):
        owners = dir_owners[dir_path]
        # Take top 2 owners with >20% share
        top_owners = [o for o in owners if o.percentage > 20.0][:3]
        if not top_owners:
            top_owners = owners[:1]

        if output_format == "gitlab":
            owner_str = " ".join(f"@{_to_username(o.author)}" for o in top_owners)
            pattern = dir_path + "/" if dir_path else "*"
            lines.append(f"{pattern} {owner_str}")
        else:
            # GitHub CODEOWNERS format
            owner_str = " ".join(f"@{_to_username(o.author)}" for o in top_owners)
            pattern = f"/{dir_path}/" if dir_path else "*"
            lines.append(f"{pattern} {owner_str}")

    content = "\n".join(lines) + "\n"
    output_path.write_text(content)


def _to_username(author: str) -> str:
    """Convert author display name to a username-like format."""
    return author.lower().replace(" ", "-")


def _aggregate_to_directories(
    ownership: dict[str, list[OwnershipEntry]],
) -> dict[str, list[OwnershipEntry]]:
    """Aggregate file ownership into directory-level ownership."""
    from collections import defaultdict

    dir_authors: dict[str, dict[str, float]] = defaultdict(lambda: defaultdict(float))

    for file_path, entries in ownership.items():
        parts = PurePosixPath(file_path).parts
        if len(parts) < 2:
            dir_path = ""
        else:
            dir_path = str(PurePosixPath(*parts[:-1]))
        for entry in entries:
            dir_authors[dir_path][entry.author] += entry.percentage

    results: dict[str, list[OwnershipEntry]] = {}
    for dir_path, authors in dir_authors.items():
        total = sum(authors.values()) or 1
        entries = [
            OwnershipEntry(author=a, percentage=round((s / total) * 100, 1))
            for a, s in authors.items()
        ]
        entries.sort(key=lambda e: e.percentage, reverse=True)
        results[dir_path] = entries

    return results
